"""workouts table

Revision ID: 9ef19e81b449
Revises: b10ac3700c2c
Create Date: 2021-03-24 19:33:46.822185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef19e81b449'
down_revision = 'b10ac3700c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('wrkt_dttm', sa.DateTime(), nullable=False),
    sa.Column('dur_sec', sa.Integer(), nullable=True),
    sa.Column('dist_mi', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pace_sec', sa.Integer(), nullable=True),
    sa.Column('gear', sa.String(length=50), nullable=True),
    sa.Column('clothes', sa.Text(), nullable=True),
    sa.Column('ele_up', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ele_down', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('hr', sa.SmallInteger(), nullable=True),
    sa.Column('cal_burn', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('training_type', sa.String(length=50), nullable=True),
    sa.Column('temp_strt', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('temp_feels_like_strt', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wethr_cond_strt', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('hmdty_strt', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wind_speed_strt', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wind_gust_strt', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('temp_end', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('temp_feels_like_end', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wethr_cond_end', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('hmdty_end', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wind_speed_end', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wind_gust_end', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('warm_up_tot_dist_mi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('warm_up_tot_tm_sec', sa.Integer(), nullable=True),
    sa.Column('warm_up_tot_pace_sec', sa.Integer(), nullable=True),
    sa.Column('cool_down_tot_dist_mi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cool_down_tot_tm_sec', sa.Integer(), nullable=True),
    sa.Column('cool_down_tot_pace_sec', sa.Integer(), nullable=True),
    sa.Column('intrvl_tot_dist_mi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('intrvl_tot_tm_sec', sa.Integer(), nullable=True),
    sa.Column('intrvl_tot_pace_sec', sa.Integer(), nullable=True),
    sa.Column('intrvl_tot_ele_up', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('intrvl_tot_ele_down', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('isrt_ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_isrt_ts'), 'workout', ['isrt_ts'], unique=False)
    op.create_index(op.f('ix_workout_type'), 'workout', ['type'], unique=False)
    op.create_index(op.f('ix_workout_wrkt_dttm'), 'workout', ['wrkt_dttm'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_wrkt_dttm'), table_name='workout')
    op.drop_index(op.f('ix_workout_type'), table_name='workout')
    op.drop_index(op.f('ix_workout_isrt_ts'), table_name='workout')
    op.drop_table('workout')
    # ### end Alembic commands ###
